server:
  port: 8080
spring:
  application:
    name: client

grpc:
  client:
    server:
      address: 'static://127.0.0.1:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext